// @ts-nocheck
import React from 'react';

const HeroSection = () => {
  return (
    <>
      <section className="elementor-section elementor-top-section elementor-element elementor-element-3a160be elementor-section-stretched elementor-section-content-top elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="3a160be" data-element_type="section" data-e-type="section" data-settings="{&quot;stretch_section&quot;:&quot;section-stretched&quot;,&quot;background_background&quot;:&quot;classic&quot;}"><div className="elementor-background-overlay"></div><div className="elementor-container elementor-column-gap-default"><div className="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-48ddf75" data-id="48ddf75" data-element_type="column" data-e-type="column"><div className="elementor-widget-wrap elementor-element-populated"><div className="elementor-element elementor-element-f397304 elementor-widget elementor-widget-heading" data-id="f397304" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default"><div className="elementor-widget-container"><h1 className="elementor-heading-title elementor-size-default"><span style={{ "color": "#ee8e09" }}>Professional</span> Security Guard Services in California</h1></div></div><div className="elementor-element elementor-element-b17eb01 elementor-widget elementor-widget-text-editor" data-id="b17eb01" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default"><div className="elementor-widget-container"><p>Licensed &amp; Insured Security Guards Serving California, Texas, Oregon &amp; Washington – Available 24/7.</p></div></div><div className="elementor-element elementor-element-e024ede elementor-hidden-desktop elementor-widget elementor-widget-image" data-id="e024ede" data-element_type="widget" data-e-type="widget" data-widget_type="image.default"><div className="elementor-widget-container">
        <img decoding="sync" width="300" height="280" src="/images/local/28-Years-Exp-1.png.webp" className="attachment-large size-large wp-image-2764" alt="Blue badge stating over 28 years of experience with laurel wreath and stars in design." fetchPriority="high" /></div></div><div className="elementor-element elementor-element-06f0688 elementor-widget elementor-widget-button" data-id="06f0688" data-element_type="widget" data-e-type="widget" data-widget_type="button.default"><div className="elementor-widget-container"><div className="elementor-button-wrapper">
          <a className="elementor-button elementor-button-link elementor-size-sm" href="https://adsguards.com/contact-us/">
            <span className="elementor-button-content-wrapper">
              <span className="elementor-button-text">CONTACT US NOW</span>
            </span>
          </a></div></div></div></div></div><div className="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-ec5f5b8" data-id="ec5f5b8" data-element_type="column" data-e-type="column"><div className="elementor-widget-wrap elementor-element-populated"><div className="elementor-element elementor-element-49973bf elementor-absolute elementor-widget__width-initial elementor-widget-mobile__width-initial elementor-hidden-tablet elementor-hidden-mobile elementor-widget elementor-widget-image" data-id="49973bf" data-element_type="widget" data-e-type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;}" data-widget_type="image.default"><div className="elementor-widget-container">
            <img decoding="async" width="500" height="500" src="/images/local/exp_for_signature-removebg-preview.png.webp" className="attachment-large size-large wp-image-4921" alt="" srcSet="/images/local/exp_for_signature-removebg-preview.png.webp 500w, /images/local/exp_for_signature-removebg-preview-300x300.png.webp 300w, /images/local/exp_for_signature-removebg-preview-150x150.png.webp 150w" sizes="(max-width: 500px) 100vw, 500px" /></div></div></div></div></div></section>
    </>
  );
};

export default HeroSection;

