"use client";
// @ts-nocheck
import React, { useState } from 'react';

const Section2 = () => {
  const [showMore1, setShowMore1] = useState(false);
  const [showMore2, setShowMore2] = useState(false);

  return (
    <>
      <section className="elementor-section elementor-top-section elementor-element elementor-element-1f6bb37 elementor-section-full_width elementor-section-stretched elementor-section-height-default elementor-section-height-default" data-id="1f6bb37" data-element_type="section" data-e-type="section" data-settings="{&quot;stretch_section&quot;:&quot;section-stretched&quot;,&quot;background_background&quot;:&quot;classic&quot;}"><div className="elementor-container elementor-column-gap-default"><div className="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-f98bd95 profile-card" data-id="f98bd95" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;animation&quot;:&quot;slideInLeft&quot;}"><div className="elementor-widget-wrap elementor-element-populated"><div className="elementor-background-overlay"></div><div className="elementor-element elementor-element-a7bf670 elementor-widget elementor-widget-image" data-id="a7bf670" data-element_type="widget" data-e-type="widget" data-widget_type="image.default"><div className="elementor-widget-container">
        <img data-lazyloaded="1" data-placeholder-resp="73x73" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI3MyIgaGVpZ2h0PSI3MyIgdmlld0JveD0iMCAwIDczIDczIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBzdHlsZT0iZmlsbDojY2ZkNGRiO2ZpbGwtb3BhY2l0eTogMC4xOyIvPjwvc3ZnPg==" loading="lazy" decoding="async" width="73" height="73" data-src="https://www.adsguards.com/wp-content/uploads/2023/02/GuardOne-Logowhite.png" className="attachment-large size-large wp-image-122" alt="Logo of GuardOne featuring a stylized G and 1 with gold and white color scheme." /></div></div><div className="elementor-element elementor-element-d4ab36d elementor-widget elementor-widget-heading" data-id="d4ab36d" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default"><div className="elementor-widget-container"><h2 className="elementor-heading-title elementor-size-default">Real-Time Guard Tracking, Reporting, and Client Updates</h2></div></div><div className={`elementor-element elementor-element-c9e7336 details-area ${showMore1 ? '' : 'content-hide'} e-flex e-con-boxed e-con e-parent`} data-id="c9e7336" data-element_type="container" data-e-type="container"><div className="e-con-inner"><div className="elementor-element elementor-element-ad20cfb elementor-widget elementor-widget-text-editor" data-id="ad20cfb" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default"><div className="elementor-widget-container"><p className="font-semibold text-xl text-white" style={{ "textAlign": "center" }}><strong>We use GuardOne to:</strong></p><ul className="list-disc list-outside px-4 text-gray-100 text-lg leading-9 text-[19px] pl-8 md:pl-0"><li>Create incident reports/activity reports and more</li><li>Create and publish security guard’s schedules</li><li>We track security guard activities</li><li>GuardOne is GPS activated</li><li>Officers activities/reports are available real time</li><li>Officers can contact ADS management directly from GuardOne</li><li>PDF reports are sent automatically to the clients</li></ul></div></div></div></div><div className={`elementor-element elementor-element-042d98e elementor-align-center show-more ${showMore1 ? 'content-hide' : ''} elementor-widget elementor-widget-button`} data-id="042d98e" data-element_type="widget" data-e-type="widget" data-widget_type="button.default"><div className="elementor-widget-container"><div className="elementor-button-wrapper">
          <a className="elementor-button elementor-button-link elementor-size-sm" href="#" onClick={(e) => { e.preventDefault(); setShowMore1(true); }}>
            <span className="elementor-button-content-wrapper">
              <span className="elementor-button-text">Show More</span>
            </span>
          </a></div></div></div><div className={`elementor-element elementor-element-59a4c60 elementor-align-center show-less ${showMore1 ? '' : 'content-hide'} elementor-widget elementor-widget-button`} data-id="59a4c60" data-element_type="widget" data-e-type="widget" data-widget_type="button.default"><div className="elementor-widget-container"><div className="elementor-button-wrapper">
            <a className="elementor-button elementor-button-link elementor-size-sm" href="#" onClick={(e) => { e.preventDefault(); setShowMore1(false); }}>
              <span className="elementor-button-content-wrapper">
                <span className="elementor-button-text">Show Less</span>
              </span>
            </a></div></div></div></div></div><div className="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-604aa78 profile-card" data-id="604aa78" data-element_type="column" data-e-type="column" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;animation&quot;:&quot;slideInRight&quot;}"><div className="elementor-widget-wrap elementor-element-populated"><div className="elementor-background-overlay"></div><div className="elementor-element elementor-element-af8692a elementor-widget elementor-widget-heading" data-id="af8692a" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default"><div className="elementor-widget-container"><h2 className="elementor-heading-title elementor-size-default">24/7 Dispatch Center</h2></div></div><div className={`elementor-element elementor-element-a2aaf12 details-area ${showMore2 ? '' : 'content-hide'} e-flex e-con-boxed e-con e-parent`} data-id="a2aaf12" data-element_type="container" data-e-type="container"><div className="e-con-inner"><div className="elementor-element elementor-element-4a0b848 elementor-widget elementor-widget-text-editor" data-id="4a0b848" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default"><div className="elementor-widget-container"><p style={{ "textAlign": "center" }}><strong>Friendly and reliable dispatch services:</strong></p><ul className="list-disc list-outside px-4 text-gray-100 text-lg leading-9 text-[19px] pl-8 md:pl-0"><li>All dispatch is control from our 24/7 central office</li><li>Live operators are available to solve problems</li><li>Dispatcher monitor security guard activities</li><li>Prompt and reliable communication with clients and guard</li><li>Officers activities/reports are available real time</li><li>Prompt response to emergency situation(s)</li></ul></div></div></div></div><div className={`elementor-element elementor-element-f0fda03 elementor-align-center show-more ${showMore2 ? 'content-hide' : ''} elementor-widget elementor-widget-button`} data-id="f0fda03" data-element_type="widget" data-e-type="widget" data-widget_type="button.default"><div className="elementor-widget-container"><div className="elementor-button-wrapper">
              <a className="elementor-button elementor-button-link elementor-size-sm" href="#" onClick={(e) => { e.preventDefault(); setShowMore2(true); }}>
                <span className="elementor-button-content-wrapper">
                  <span className="elementor-button-text">Show More</span>
                </span>
              </a></div></div></div><div className={`elementor-element elementor-element-4f7cf3e elementor-align-center show-less ${showMore2 ? '' : 'content-hide'} elementor-widget elementor-widget-button`} data-id="4f7cf3e" data-element_type="widget" data-e-type="widget" data-widget_type="button.default"><div className="elementor-widget-container"><div className="elementor-button-wrapper">
                <a className="elementor-button elementor-button-link elementor-size-sm" href="#" onClick={(e) => { e.preventDefault(); setShowMore2(false); }}>
                  <span className="elementor-button-content-wrapper">
                    <span className="elementor-button-text">Show Less</span>
                  </span>
                </a></div></div></div></div></div></div></section>
    </>
  );
};

export default Section2;
