// @ts-nocheck
import React from 'react';
import AnimatedShowMore from '../ui/AnimatedShowMore';

const ServicesSection_3 = () => {
  return (
    <>
      <section className="elementor-section elementor-top-section elementor-element elementor-element-e5066b8 elementor-section-height-min-height elementor-section-boxed elementor-section-height-default elementor-section-items-middle" data-id="e5066b8" data-element_type="section" data-e-type="section" data-settings="{&quot;background_background&quot;:&quot;classic&quot;}"><div className="elementor-container elementor-column-gap-default"><div className="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-2f6b6df" data-id="2f6b6df" data-element_type="column" data-e-type="column"><div className="elementor-widget-wrap elementor-element-populated"><div className="elementor-element elementor-element-c02854c elementor-widget elementor-widget-image" data-id="c02854c" data-element_type="widget" data-e-type="widget" data-widget_type="image.default"><div className="elementor-widget-container">
<img    decoding="async" src="/images/local/ChatGPT-Image-Aug-8-2026-06_54_18-PM-1-rrnvq0nhmccvgsxtbrakvem04hlfc9h22fsklo563c.png" title="ChatGPT Image Aug 8, 2026, 06_54_18 PM (1)" alt="ChatGPT Image Aug 8, 2026, 06_54_18 PM (1)" loading="lazy" width="500" height="540" /></div></div></div></div><div className="elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-e50cc40 profile-cardabout" data-id="e50cc40" data-element_type="column" data-e-type="column"><div className="elementor-widget-wrap elementor-element-populated"><div className="elementor-element elementor-element-a990fdb elementor-widget elementor-widget-heading" data-id="a990fdb" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default"><div className="elementor-widget-container"><h2 className="elementor-heading-title elementor-size-default">Why California Businesses Choose ADS Guards</h2></div></div><div className="elementor-element elementor-element-3da4d4d elementor-widget elementor-widget-heading" data-id="3da4d4d" data-element_type="widget" data-e-type="widget" data-widget_type="heading.default"><div className="elementor-widget-container"><h2 className="elementor-heading-title elementor-size-default">California Security Guard Services You Can Trust</h2></div></div><div className="elementor-element elementor-element-55d5fb0 elementor-widget elementor-widget-text-editor" data-id="55d5fb0" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default"><div className="elementor-widget-container"><p>Trusted Security Guard Company in California Since 1997</p></div></div><div className="elementor-element elementor-element-19cb1e1 elementor-widget elementor-widget-text-editor" data-id="19cb1e1" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default"><div className="elementor-widget-container"><p data-start="487" data-end="799">At ADS Guards, we ensure your business receives the most professional security guard services in California. We provide customizable security solutions tailored to your needs, whether you require armed or unarmed security guards, event security, or commercial and residential protection.</p><p data-start="801" data-end="1056">Our licensed California security guards are trained to protect your property, employees, and assets with professionalism and vigilance. As your business grows, our security services evolve with you to ensure maximum protection and peace of mind.</p><p data-start="1058" data-end="1230">We are committed to delivering the best security guards in California, providing 24/7 on-site security, patrol services, and emergency response solutions.</p><p data-start="1232" data-end="1406">Remember, unwanted events can happen anytime. A mindset of “it can’t happen to me” won’t help — but having ADS Guards, your trusted California security company, will.</p></div></div><AnimatedShowMore buttonAlignment="left">
      <div className="elementor-element elementor-element-83f22b9 details-areaabout e-flex e-con-boxed e-con e-parent" data-id="83f22b9" data-element_type="container" data-e-type="container">
        <div className="e-con-inner">
          <div className="elementor-element elementor-element-aae0780 elementor-widget elementor-widget-text-editor" data-id="aae0780" data-element_type="widget" data-e-type="widget" data-widget_type="text-editor.default">
            <div className="elementor-widget-container">
              <p className="text-gray-200 font-semibold tracking-wide"><strong>Theft<br /></strong><strong>Damage<br /></strong><strong>Property destruction</strong></p>
              <p className="text-justify text-gray-400 mb-5">At ADS Guards, we make it our mission to provide you with top class security guard services. Therefore, they add value to your company. Being safe enables you to focus on your mission. Certainly, together we can improve our community! Technology driven security at ADS Security Guards Service uses cutting edge mobile technology. Above all, it is updated, backed-up and fully reliant. As a result, it enables us to stay on top of all our systems. So, it helps as we receive daily reports – complete and thorough. Our reports provide a full insight. We look at duties completed by ADS trained security guards. That helps us assess their process. It manages their interaction with your employees and your environment. With the help of professional risk assessors, we fully optimize your security needs.<span className="text-primary cursor-pointer">&nbsp;</span></p>
            </div>
          </div>
        </div>
      </div>
    </AnimatedShowMore></div></div></div></section>
    </>
  );
};

export default ServicesSection_3;
