// Generated by scripts/bundle-css.cjs. Do not edit.
export const SITE_STYLESHEET = '/wp-content/litespeed/css/site.bundle.css?v=785526c57b';
export const EDITOR_STYLESHEET = '/wp-content/litespeed/css/editor.bundle.css?v=426402d406';
