/**
 * Inline <style> blocks from the original Elementor HTML widgets, kept
 * verbatim. They are global rules whose cascade order matters, so they are
 * emitted at the same positions as in the original markup.
 */
export const DESKTOP_GRID_STYLES = [
  "\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-white {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t--tw-text-opacity: 1;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcolor: rgb(255 255 255/var(--tw-text-opacity))\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.tracking-wider {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tletter-spacing: .05em\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.font-light {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-weight: 500\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-xl {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-size: 5rem\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-lg,\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-xl {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tline-height: 1.75rem\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-gray-400 {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t--tw-text-opacity: 1;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcolor: rgb(156 163 175/var(--tw-text-opacity))\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
  "\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-white {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t--tw-text-opacity: 1;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcolor: rgb(255 255 255/var(--tw-text-opacity))\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.tracking-wider {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tletter-spacing: .05em\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.font-light {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-weight: 500\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-xl {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-size: 1.25rem\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-lg,\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-xl {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tline-height: 1.75rem\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-gray-400 {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t--tw-text-opacity: 1;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcolor: rgb(156 163 175/var(--tw-text-opacity))\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.px-3 {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcolor: #fff\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-2xl {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-size: 1.5rem;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tline-height: 2rem;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbackground-color: #fff\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t",
  "\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-white {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t--tw-text-opacity: 1;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcolor: rgb(255 255 255/var(--tw-text-opacity))\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.tracking-wider {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tletter-spacing: .05em\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.font-light {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-weight: 500\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-xl {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-size: 1.25rem\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-lg,\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-xl {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tline-height: 1.75rem\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-gray-400 {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t--tw-text-opacity: 1;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcolor: rgb(156 163 175/var(--tw-text-opacity))\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.px-3 {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbackground-color: #000\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
];

export const MOBILE_GRID_STYLES = [
  "\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.px-3 {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tbackground-color: #171717;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-family: Plus Jakarta, sans-serif;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-size: 24px;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-weight: 100\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-xl {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-weight: 300;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-size: 1.25rem;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-family: Plus Jakarta, sans-serif\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text-gray-400 {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-family: Plus Jakarta, sans-serif;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfont-size: 16px\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.pb-3 {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpadding-bottom: .75rem\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.px-3 {\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpadding-left: .75rem;\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpadding-right: .75rem\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t"
];
